provider "aws"{
    region="us-east-1"
}


### IMPORTANT FOR MIGRATION FROM AWS OR ANYWHERE TO TERRAFORM##

#EXAMPLE##


import{
    id=""  ### NAME OF AMI OR ID WRT THIS SCENARIO
    to= aws_instance.example   ### ANY RESOURCE AND NAME OF RESOURCE ###
}


### IMPORT TO GENERATE THE OUTPUT FILE , THEN COPY THE GENERATED FILE TO MAIN.TF, NEXT COMMAND TO PUSH THE CHANGES TO STATEFILE SO THAT IT UNDERSTAND NOT TO CREATE A NEW INSTANCE.
